PackageIdentifier: kaanreal.henkan
PackageVersion: 1.2.0
PackageLocale: en-US
Publisher: kaanreal
PublisherUrl: https://github.com/kaanreal
PublisherSupportUrl: https://github.com/kaanreal/henkan/issues
Author: kaanreal
PackageName: Henkan
PackageUrl: https://github.com/kaanreal/henkan
License: MIT
LicenseUrl: https://github.com/kaanreal/henkan/blob/main/LICENSE
ShortDescription: osu!mania to Etterna / StepMania beatmap converter
Description: A cross-platform desktop and CLI tool for converting beatmaps.
Moniker: henkan
Tags: osu, osu-mania, etterna, stepmania, beatmap, converter
ManifestType: defaultLocale
ManifestVersion: 1.6.0
