PackageIdentifier: kaanreal.henkan
PackageVersion: 1.2.0
InstallerLocale: en-US
InstallerType: wix
InstallerSwitches:
  Silent: /quiet /norestart
  SilentWithProgress: /passive /norestart
ProductCode: "{CHANGE_ME}"
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/kaanreal/henkan/releases/download/v1.2.0/Henkan_1.2.0_x64_en-US.msi
    InstallerSha256: 1b67d7b9a8412c5f400ae959bae72bffd1b3610b778afbdbc32d29f25c76538d
ManifestType: installer
ManifestVersion: 1.6.0
