PackageIdentifier: kaanreal.henkan
PackageVersion: 1.5.1
InstallerLocale: en-US
InstallerType: nullsoft
InstallerSwitches:
  Silent: /S
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/kaanreal/henkan/releases/download/v1.5.1/Henkan-v1.5.1-windows-setup.exe
    InstallerSha256: 8715a05f90ddb52c05528120ab766fb598060704593dcf52e1a6f074f6a8f092
ManifestType: installer
ManifestVersion: 1.6.0
